language: python

python:
  - "3.8"

branches:
  only:
    - master

services:
  - docker

install:
  - docker build -t anonguy/anonchat:latest site
  - pip install -r requirements-ci.txt

script:
  - flake8 site
  - docker run --env-file development.env -e DEBUG="" anonguy/anonchat:latest /usr/src/app/anonchat/manage.py test api

deploy:
  provider: script
  script: bash deploy.sh

cache: pip
