version: '2.0'


services:

  database:
    image: postgres:12-alpine
    env_file: .env

  redis:
    image: redis:5

  site:
    image: aperture/anonchat:latest
    command: daphne -b 0.0.0.0 -p 8000 anonchat.asgi:application
    volumes:
      - ./static:/static
    expose:
      - 8000
    depends_on:
      - database
      - redis
    env_file: .env

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/static
    depends_on:
      - site
    ports:
      - 8000:80
